<?php

/**
 * @file
 */

/**
 * Implements hook_node_view().
 */

/**
 *
 */
function redlink_node_view($node, $view_mode) {
  dsm($node);
  dsm($view_mode);
  if ($node->type == 'article') {
    // code...
    $link_text = t('Delete this node');
    $link_options = array(
      'attributes' => array('style' => 'color:#ff0000'),
    );
    $link_markup = l($link_text, "node/$node->nid/delete", $link_options);

    $node->content['redlink'] = array();
    $form['selected'] = array(
      '#type' => 'select',
      '#title' => t('Selected'),
      '#options' => array(
        0 => t('No'),
        1 => t('Yes'),
      ),
       // '#default_value' => $category['selected'],.
      '#description' => t('Set this to <em>Yes</em> if you would like this category to be selected by default.'),
    );

    $node->content['redlink']['#markup'] = drupal_render($form['selected']);
  }
}
